import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';
import { CatalogPageComponent } from './pages/catalog-page/catalog-page.component';
import { CartPageComponent } from './pages/cart-page/cart-page.component';
import { CheckoutPageComponent } from './pages/checkout-page/checkout-page.component';
import { LoginPageComponent } from './pages/login-page/login-page.component';
import { RegisterPageComponent } from './pages/register-page/register-page.component';
import { OperationsPageComponent } from './pages/operations-page/operations-page.component';
import { PasswordRecoveryPageComponent } from './pages/password-recovery-page/password-recovery-page.component';
import { ProfilePageComponent } from './pages/profile-page/profile-page.component';
import { ProductDetailPageComponent } from './pages/product-detail-page/product-detail-page.component';
import { PurchasesPageComponent } from './pages/purchases-page/purchases-page.component';
import { FavoritesPageComponent } from './pages/favorites-page/favorites-page.component';
import { PqrsPageComponent } from './pages/pqrs-page/pqrs-page.component';
import { LogisticsHubPageComponent } from './pages/logistics-hub-page/logistics-hub-page.component';
import { SellerPortalComponent } from './pages/seller-portal/seller-portal.component';
import { NotificationsPageComponent } from './pages/notifications-page/notifications-page.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'login', component: LoginPageComponent },
  { path: 'registro', component: RegisterPageComponent },
  { path: 'recuperar-clave', component: PasswordRecoveryPageComponent },
  { path: 'perfil', component: ProfilePageComponent },
  { path: 'mis-compras', component: PurchasesPageComponent },
  { path: 'favoritos', component: FavoritesPageComponent },
  { path: 'notificaciones', component: NotificationsPageComponent },
  { path: 'pqrs', component: PqrsPageComponent },
  { path: 'catalogo', component: CatalogPageComponent },
  { path: 'producto/:id', component: ProductDetailPageComponent },
  { path: 'carrito', component: CartPageComponent },
  { path: 'checkout', component: CheckoutPageComponent },
  { path: 'operaciones', component: OperationsPageComponent },
  { path: 'logistica', component: LogisticsHubPageComponent },
  { path: 'vendedor', component: SellerPortalComponent },
];
